[package]
name = "libmessages-sys"
version = "0.1.1"
authors = ["Michael Watzko <michael@watzko.de>"]

[dependencies]
log = "0.4.1"
libc = "0.2.40"

[build-dependencies]
gcc = "0.3.54"
bindgen = "0.35.0"
