pipeline {
    agent any
    environment {
        CARGO = '$HOME/.cargo/bin/cargo'
        RUSTUP = '$HOME/.cargo/bin/rustup'
    }
  dir('source/mecview_server') {
    stages {
        stage('prepare') {
            steps {
                sh "curl https://sh.rustup.rs -sSf | sh -s -- -y"
                sh "$RUSTUP install beta"
                sh "$RUSTUP install nightly"
                sh "$RUSTUP update"
                sh "$CARGO +nightly install clippy"
            }
        }
        stage('Build') {
            steps {
                sh "$CARGO +beta build"
            }
        }
        stage('Test') {
            steps {
                sh "$CARGO +beta test"
            }
        }
        stage('Clippy') {
            steps {
                sh "$CARGO +nightly clippy --all"
            }
        }
        stage('Rustfmt') {
            steps {
                // The build will fail if rustfmt thinks any changes are
                // required.
                sh "$CARGO +nightly fmt --all -- --write-mode diff"
            }
        }
        stage('Doc') {
            steps {
                sh "$CARGO doc"
                // We run a python `SimpleHTTPServer` against
                // /var/lib/jenkins/jobs/<repo>/branches/master/javadoc to
                // display our docs
                step([$class: 'JavadocArchiver',
                      javadocDir: 'target/doc',
                      keepAll: false])
            }
        }
    }
  }
}
