/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewGeneralModule"
 * 	found in "/home/mi7wa6/Dokumente/mecview_2018-05-18/MECViewServerSDK/proto/general.asn1"
 * 	`asn1c -fcompound-names -Werror -gen-PER`
 */

#ifndef	_ObjectType_H_
#define	_ObjectType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ObjectType {
	ObjectType_not_classified	= 0,
	ObjectType_pedestrian	= 1,
	ObjectType_car	= 2,
	ObjectType_van_or_transporter	= 3,
	ObjectType_truck	= 4,
	ObjectType_bus	= 5,
	ObjectType_motorbike	= 6,
	ObjectType_bicycle	= 7,
	ObjectType_optional_1	= 8,
	ObjectType_optional_2	= 9,
	ObjectType_optinal_3	= 10
} e_ObjectType;

/* ObjectType */
typedef long	 ObjectType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ObjectType;
asn_struct_free_f ObjectType_free;
asn_struct_print_f ObjectType_print;
asn_constr_check_f ObjectType_constraint;
ber_type_decoder_f ObjectType_decode_ber;
der_type_encoder_f ObjectType_encode_der;
xer_type_decoder_f ObjectType_decode_xer;
xer_type_encoder_f ObjectType_encode_xer;
per_type_decoder_f ObjectType_decode_uper;
per_type_encoder_f ObjectType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ObjectType_H_ */
#include <asn_internal.h>
