/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewEnvironmentModule"
 * 	found in "/home/mi7wa6/Dokumente/2018-BA-Watzko/source/ffi_test/libmessage_test/cpp/MECViewServerSDK/proto/environment.asn1"
 * 	`asn1c -fcompound-names -fskeletons-copy -fnative-types`
 */

#ifndef	_EnvironmentEnvelope_H_
#define	_EnvironmentEnvelope_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "ReferencePoint.h"
#include "Errors.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EnvironmentEnvelope */
typedef struct EnvironmentEnvelope {
	long	 version;
	long	 server_id;
	ReferencePoint_t	 reference_point;
	Errors_t	 error_codes;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EnvironmentEnvelope_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EnvironmentEnvelope;

#ifdef __cplusplus
}
#endif

#endif	/* _EnvironmentEnvelope_H_ */
#include <asn_internal.h>
