/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewProtocolModule"
 * 	found in "/home/mi7wa6/Dokumente/2018-BA-Watzko/source/ffi_test/libmessage_test/cpp/MECViewServerSDK/proto/protocol.asn1"
 * 	`asn1c -fcompound-names -fskeletons-copy -fnative-types`
 */

#ifndef	_SubscriptionStatus_H_
#define	_SubscriptionStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SubscriptionStatus {
	SubscriptionStatus_unsubscribed	= 0,
	SubscriptionStatus_subscribed	= 1
} e_SubscriptionStatus;

/* SubscriptionStatus */
typedef long	 SubscriptionStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SubscriptionStatus;
asn_struct_free_f SubscriptionStatus_free;
asn_struct_print_f SubscriptionStatus_print;
asn_constr_check_f SubscriptionStatus_constraint;
ber_type_decoder_f SubscriptionStatus_decode_ber;
der_type_encoder_f SubscriptionStatus_encode_der;
xer_type_decoder_f SubscriptionStatus_decode_xer;
xer_type_encoder_f SubscriptionStatus_encode_xer;
per_type_decoder_f SubscriptionStatus_decode_uper;
per_type_encoder_f SubscriptionStatus_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SubscriptionStatus_H_ */
#include <asn_internal.h>
