/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewProtocolModule"
 * 	found in "/home/mi7wa6/Dokumente/2018-BA-Watzko/source/libmessages-sys/cpp/MECViewServerSDK/proto/protocol.asn1"
 * 	`asn1c -fcompound-names -fskeletons-copy -fnative-types -gen-PER`
 */

#ifndef	_ClientRegistration_H_
#define	_ClientRegistration_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ClientType.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CoveredArea;

/* ClientRegistration */
typedef struct ClientRegistration {
	ClientType_t	 type;
	struct CoveredArea	*covered_area	/* OPTIONAL */;
	long	*minimum_message_period	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ClientRegistration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ClientRegistration;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CoveredArea.h"

#endif	/* _ClientRegistration_H_ */
#include <asn_internal.h>
