/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewEnvironmentModule"
 * 	found in "/home/mi7wa6/Dokumente/2018-BA-Watzko/source/libmessages-sys/cpp/MECViewServerSDK/proto/environment.asn1"
 * 	`asn1c -fcompound-names -fskeletons-copy -fnative-types -gen-PER`
 */

#include "Covariance.h"

static int
memb_north_pos_east_pos_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -225000000 && value <= 225000000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_north_pos_north_vel_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -9000000 && value <= 9000000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_north_pos_east_vel_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -9000000 && value <= 9000000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_east_pos_north_vel_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -9000000 && value <= 9000000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_east_pos_east_vel_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -9000000 && value <= 9000000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_north_vel_east_vel_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -360000 && value <= 360000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_north_pos_east_pos_constr_2 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 29, -1, -225000000,  225000000 }	/* (-225000000..225000000) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_north_pos_north_vel_constr_3 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 25, -1, -9000000,  9000000 }	/* (-9000000..9000000) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_north_pos_east_vel_constr_4 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 25, -1, -9000000,  9000000 }	/* (-9000000..9000000) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_east_pos_north_vel_constr_5 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 25, -1, -9000000,  9000000 }	/* (-9000000..9000000) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_east_pos_east_vel_constr_6 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 25, -1, -9000000,  9000000 }	/* (-9000000..9000000) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_north_vel_east_vel_constr_7 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 20, -1, -360000,  360000 }	/* (-360000..360000) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_Covariance_1[] = {
	{ ATF_POINTER, 6, offsetof(struct Covariance, north_pos_east_pos),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_north_pos_east_pos_constraint_1,
		&asn_PER_memb_north_pos_east_pos_constr_2,
		0,
		"north-pos-east-pos"
		},
	{ ATF_POINTER, 5, offsetof(struct Covariance, north_pos_north_vel),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_north_pos_north_vel_constraint_1,
		&asn_PER_memb_north_pos_north_vel_constr_3,
		0,
		"north-pos-north-vel"
		},
	{ ATF_POINTER, 4, offsetof(struct Covariance, north_pos_east_vel),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_north_pos_east_vel_constraint_1,
		&asn_PER_memb_north_pos_east_vel_constr_4,
		0,
		"north-pos-east-vel"
		},
	{ ATF_POINTER, 3, offsetof(struct Covariance, east_pos_north_vel),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_east_pos_north_vel_constraint_1,
		&asn_PER_memb_east_pos_north_vel_constr_5,
		0,
		"east-pos-north-vel"
		},
	{ ATF_POINTER, 2, offsetof(struct Covariance, east_pos_east_vel),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_east_pos_east_vel_constraint_1,
		&asn_PER_memb_east_pos_east_vel_constr_6,
		0,
		"east-pos-east-vel"
		},
	{ ATF_POINTER, 1, offsetof(struct Covariance, north_vel_east_vel),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_north_vel_east_vel_constraint_1,
		&asn_PER_memb_north_vel_east_vel_constr_7,
		0,
		"north-vel-east-vel"
		},
};
static const int asn_MAP_Covariance_oms_1[] = { 0, 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_Covariance_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Covariance_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* north-pos-east-pos */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* north-pos-north-vel */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* north-pos-east-vel */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* east-pos-north-vel */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* east-pos-east-vel */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* north-vel-east-vel */
};
static asn_SEQUENCE_specifics_t asn_SPC_Covariance_specs_1 = {
	sizeof(struct Covariance),
	offsetof(struct Covariance, _asn_ctx),
	asn_MAP_Covariance_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_Covariance_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Covariance = {
	"Covariance",
	"Covariance",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Covariance_tags_1,
	sizeof(asn_DEF_Covariance_tags_1)
		/sizeof(asn_DEF_Covariance_tags_1[0]), /* 1 */
	asn_DEF_Covariance_tags_1,	/* Same as above */
	sizeof(asn_DEF_Covariance_tags_1)
		/sizeof(asn_DEF_Covariance_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Covariance_1,
	6,	/* Elements count */
	&asn_SPC_Covariance_specs_1	/* Additional specs */
};

