/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewEnvironmentModule"
 * 	found in "/home/mi7wa6/Dokumente/2018-BA-Watzko/source/libmessages-sys/cpp/MECViewServerSDK/proto/environment.asn1"
 * 	`asn1c -fcompound-names -fskeletons-copy -fnative-types -gen-PER`
 */

#ifndef	_EnvironmentObjectDetection_H_
#define	_EnvironmentObjectDetection_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include "PositionOffset.h"
#include "ObjectType.h"
#include "ObjectSize.h"
#include "Covariance.h"
#include "PredictedPath.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MovingVector;

/* EnvironmentObjectDetection */
typedef struct EnvironmentObjectDetection {
	long	 timestamp;
	BOOLEAN_t	 measured;
	long	 global_id;
	long	 probability_of_existence;
	PositionOffset_t	 position_offset;
	struct MovingVector	*moving_vector	/* OPTIONAL */;
	ObjectType_t	 type;
	long	 type_probability;
	ObjectSize_t	 size;
	Covariance_t	 covariance;
	long	 orientation;
	long	 std_dev_orientation;
	PredictedPath_t	 predicted_path;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EnvironmentObjectDetection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EnvironmentObjectDetection;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MovingVector.h"

#endif	/* _EnvironmentObjectDetection_H_ */
#include <asn_internal.h>
