/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewGeneralModule"
 * 	found in "/home/mi7wa6/Dokumente/2018-BA-Watzko/source/ffi_test/libmessage_test/cpp/MECViewServerSDK/proto/general.asn1"
 * 	`asn1c -fcompound-names -fskeletons-copy -fnative-types`
 */

#ifndef	_MovingVector_H_
#define	_MovingVector_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MovingVector */
typedef struct MovingVector {
	long	 velocity_north;
	long	 velocity_east;
	long	*std_dev_velocity_north	/* OPTIONAL */;
	long	*std_dev_velocity_east	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MovingVector_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MovingVector;

#ifdef __cplusplus
}
#endif

#endif	/* _MovingVector_H_ */
#include <asn_internal.h>
