/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewGeneralModule"
 * 	found in "/home/mi7wa6/Dokumente/2018-BA-Watzko/source/ffi_test/libmessage_test/cpp/MECViewServerSDK/proto/general.asn1"
 * 	`asn1c -fcompound-names -fskeletons-copy -fnative-types`
 */

#include "PositionOffset.h"

static int
memb_position_north_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -15000 && value <= 15000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_position_east_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -15000 && value <= 15000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_std_dev_position_north_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -15000 && value <= 15000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_std_dev_position_east_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -15000 && value <= 15000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_position_north_constr_2 = {
	{ APC_CONSTRAINED,	 15,  15, -15000,  15000 }	/* (-15000..15000) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_position_east_constr_3 = {
	{ APC_CONSTRAINED,	 15,  15, -15000,  15000 }	/* (-15000..15000) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_std_dev_position_north_constr_4 = {
	{ APC_CONSTRAINED,	 15,  15, -15000,  15000 }	/* (-15000..15000) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_std_dev_position_east_constr_5 = {
	{ APC_CONSTRAINED,	 15,  15, -15000,  15000 }	/* (-15000..15000) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_PositionOffset_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PositionOffset, position_north),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_position_north_constraint_1,
		&asn_PER_memb_position_north_constr_2,
		0,
		"position-north"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PositionOffset, position_east),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_position_east_constraint_1,
		&asn_PER_memb_position_east_constr_3,
		0,
		"position-east"
		},
	{ ATF_POINTER, 2, offsetof(struct PositionOffset, std_dev_position_north),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_std_dev_position_north_constraint_1,
		&asn_PER_memb_std_dev_position_north_constr_4,
		0,
		"std-dev-position-north"
		},
	{ ATF_POINTER, 1, offsetof(struct PositionOffset, std_dev_position_east),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_std_dev_position_east_constraint_1,
		&asn_PER_memb_std_dev_position_east_constr_5,
		0,
		"std-dev-position-east"
		},
};
static int asn_MAP_PositionOffset_oms_1[] = { 2, 3 };
static ber_tlv_tag_t asn_DEF_PositionOffset_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_PositionOffset_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* position-north at 15 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* position-east at 16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* std-dev-position-north at 17 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* std-dev-position-east at 18 */
};
static asn_SEQUENCE_specifics_t asn_SPC_PositionOffset_specs_1 = {
	sizeof(struct PositionOffset),
	offsetof(struct PositionOffset, _asn_ctx),
	asn_MAP_PositionOffset_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_PositionOffset_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PositionOffset = {
	"PositionOffset",
	"PositionOffset",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PositionOffset_tags_1,
	sizeof(asn_DEF_PositionOffset_tags_1)
		/sizeof(asn_DEF_PositionOffset_tags_1[0]), /* 1 */
	asn_DEF_PositionOffset_tags_1,	/* Same as above */
	sizeof(asn_DEF_PositionOffset_tags_1)
		/sizeof(asn_DEF_PositionOffset_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PositionOffset_1,
	4,	/* Elements count */
	&asn_SPC_PositionOffset_specs_1	/* Additional specs */
};

