/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewGeneralModule"
 * 	found in "/home/mi7wa6/Dokumente/2018-BA-Watzko/source/libmessages-sys/cpp/MECViewServerSDK/proto/general.asn1"
 * 	`asn1c -fcompound-names -fskeletons-copy -fnative-types -gen-PER`
 */

#ifndef	_PositionOffset_H_
#define	_PositionOffset_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PositionOffset */
typedef struct PositionOffset {
	long	 position_north;
	long	 position_east;
	long	*std_dev_position_north	/* OPTIONAL */;
	long	*std_dev_position_east	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PositionOffset_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PositionOffset;

#ifdef __cplusplus
}
#endif

#endif	/* _PositionOffset_H_ */
#include <asn_internal.h>
