/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewSensorModule"
 * 	found in "/home/mi7wa6/Dokumente/2018-BA-Watzko/source/ffi_test/libmessage_test/cpp/MECViewServerSDK/proto/sensor.asn1"
 * 	`asn1c -fcompound-names -fskeletons-copy -fnative-types`
 */

#ifndef	_SensorType_H_
#define	_SensorType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SensorType {
	SensorType_server	= 0,
	SensorType_cam	= 1,
	SensorType_lidar	= 2
} e_SensorType;

/* SensorType */
typedef long	 SensorType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SensorType;
asn_struct_free_f SensorType_free;
asn_struct_print_f SensorType_print;
asn_constr_check_f SensorType_constraint;
ber_type_decoder_f SensorType_decode_ber;
der_type_encoder_f SensorType_encode_der;
xer_type_decoder_f SensorType_decode_xer;
xer_type_encoder_f SensorType_encode_xer;
per_type_decoder_f SensorType_decode_uper;
per_type_encoder_f SensorType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SensorType_H_ */
#include <asn_internal.h>
