/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewSensorModule"
 * 	found in "/home/mi7wa6/Dokumente/2018-BA-Watzko/source/libmessages-sys/cpp/MECViewServerSDK/proto/sensor.asn1"
 * 	`asn1c -fcompound-names -fskeletons-copy -fnative-types -gen-PER`
 */

#ifndef	_SensorObjectDetections_H_
#define	_SensorObjectDetections_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SensorObjectDetection;

/* SensorObjectDetections */
typedef struct SensorObjectDetections {
	A_SEQUENCE_OF(struct SensorObjectDetection) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SensorObjectDetections_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SensorObjectDetections;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SensorObjectDetection.h"

#endif	/* _SensorObjectDetections_H_ */
#include <asn_internal.h>
