/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewProtocolModule"
 * 	found in "/home/mi7wa6/Dokumente/2018-BA-Watzko/source/libmessages-sys/cpp/MECViewServerSDK/proto/protocol.asn1"
 * 	`asn1c -fcompound-names -fskeletons-copy -fnative-types -gen-PER`
 */

#include "UpdateStatus.h"

static asn_TYPE_member_t asn_MBR_UpdateStatus_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UpdateStatus, sensor_status),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ConnectionStatus,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sensor-status"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UpdateStatus, ip_address),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ip-address"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UpdateStatus, sensor_id),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sensor-id"
		},
};
static const ber_tlv_tag_t asn_DEF_UpdateStatus_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UpdateStatus_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sensor-status */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ip-address */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* sensor-id */
};
static asn_SEQUENCE_specifics_t asn_SPC_UpdateStatus_specs_1 = {
	sizeof(struct UpdateStatus),
	offsetof(struct UpdateStatus, _asn_ctx),
	asn_MAP_UpdateStatus_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_UpdateStatus = {
	"UpdateStatus",
	"UpdateStatus",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_UpdateStatus_tags_1,
	sizeof(asn_DEF_UpdateStatus_tags_1)
		/sizeof(asn_DEF_UpdateStatus_tags_1[0]), /* 1 */
	asn_DEF_UpdateStatus_tags_1,	/* Same as above */
	sizeof(asn_DEF_UpdateStatus_tags_1)
		/sizeof(asn_DEF_UpdateStatus_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_UpdateStatus_1,
	3,	/* Elements count */
	&asn_SPC_UpdateStatus_specs_1	/* Additional specs */
};

