[package]
name = "libmessage_test"
version = "0.1.0"
authors = ["Michael Watzko <michael@watzko.de>"]
build = "build.rs"


[dependencies]
libc = "0.2.0"

[build-dependencies]
cc = "1.0"
gcc = "*"
bindgen = "0.26.3"