/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewRoadClearanceModule"
 * 	found in "/home/mi7wa6/Dokumente/mecview_2018-05-18/MECViewServerSDK/proto/road_clearance.asn1"
 * 	`asn1c -fcompound-names -Werror -gen-PER`
 */

#ifndef	_RoadClearanceFrame_H_
#define	_RoadClearanceFrame_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Header.h"
#include "RoadClearanceEnvelope.h"
#include "RoadSections.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RoadClearanceFrame */
typedef struct RoadClearanceFrame {
	Header_t	 header;
	RoadClearanceEnvelope_t	 envelope;
	RoadSections_t	 road_sections;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadClearanceFrame_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadClearanceFrame;

#ifdef __cplusplus
}
#endif

#endif	/* _RoadClearanceFrame_H_ */
#include <asn_internal.h>
