/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewProtocolModule"
 * 	found in "/home/mi7wa6/Dokumente/mecview_2018-05-18/MECViewServerSDK/proto/protocol.asn1"
 * 	`asn1c -fcompound-names -Werror -gen-PER`
 */

#ifndef	_CoveredArea_H_
#define	_CoveredArea_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ReferencePoint;

/* CoveredArea */
typedef struct CoveredArea {
	A_SEQUENCE_OF(struct ReferencePoint) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CoveredArea_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CoveredArea;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ReferencePoint.h"

#endif	/* _CoveredArea_H_ */
#include <asn_internal.h>
