/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewRoadClearanceModule"
 * 	found in "/home/mi7wa6/Dokumente/2018-BA-Watzko/source/libsdk-sys/cpp/MECViewServerSDK/proto/road_clearance.asn1"
 * 	`asn1c -fcompound-names -fskeletons-copy -fnative-types -gen-PER`
 */

#ifndef	_Parameter_H_
#define	_Parameter_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ReferencePoint;

/* Parameter */
typedef struct Parameter {
	long	 id;
	UTF8String_t	 name;
	long	 value;
	struct ReferencePoint	*position	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Parameter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Parameter;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ReferencePoint.h"

#endif	/* _Parameter_H_ */
#include <asn_internal.h>
