/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewEnvironmentModule"
 * 	found in "/home/mi7wa6/Dokumente/2018-BA-Watzko/source/libsdk-sys/cpp/MECViewServerSDK/proto/environment.asn1"
 * 	`asn1c -fcompound-names -fskeletons-copy -fnative-types -gen-PER`
 */

#ifndef	_PathPoint_H_
#define	_PathPoint_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PositionOffset.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PathPoint */
typedef struct PathPoint {
	PositionOffset_t	 position_offset;
	long	 probybility;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PathPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PathPoint;

#ifdef __cplusplus
}
#endif

#endif	/* _PathPoint_H_ */
#include <asn_internal.h>
