/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewRoadClearanceModule"
 * 	found in "/home/mi7wa6/Dokumente/2018-BA-Watzko/source/libsdk-sys/cpp/MECViewServerSDK/proto/road_clearance.asn1"
 * 	`asn1c -fcompound-names -fskeletons-copy -fnative-types -gen-PER`
 */

#ifndef	_RoadSection_H_
#define	_RoadSection_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "Parameters.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RoadSection */
typedef struct RoadSection {
	long	 geo_fence_id;
	Parameters_t	 parameters;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadSection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadSection;

#ifdef __cplusplus
}
#endif

#endif	/* _RoadSection_H_ */
#include <asn_internal.h>
