/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewSensorModule"
 * 	found in "/home/mi7wa6/Dokumente/mecview_2018-05-18/MECViewServerSDK/proto/sensor.asn1"
 * 	`asn1c -fcompound-names -Werror -gen-PER`
 */

#ifndef	_SensorIdleFrame_H_
#define	_SensorIdleFrame_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SensorIdleFrame */
typedef struct SensorIdleFrame {
	long	 version;
	long	 sender_id;
	long	 pole_id;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SensorIdleFrame_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SensorIdleFrame;

#ifdef __cplusplus
}
#endif

#endif	/* _SensorIdleFrame_H_ */
#include <asn_internal.h>
