/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MECViewSensorModule"
 * 	found in "/home/mi7wa6/Dokumente/mecview_2018-05-18/MECViewServerSDK/proto/sensor.asn1"
 * 	`asn1c -fcompound-names -Werror -gen-PER`
 */

#ifndef	_SensorFrame_H_
#define	_SensorFrame_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Header.h"
#include "SensorEnvelope.h"
#include "SensorObjectDetections.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SensorFrame */
typedef struct SensorFrame {
	Header_t	 header;
	SensorEnvelope_t	 envelope;
	SensorObjectDetections_t	 object_detections;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SensorFrame_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SensorFrame;

#ifdef __cplusplus
}
#endif

#endif	/* _SensorFrame_H_ */
#include <asn_internal.h>
